services:
  - type: web
    name: charm-shiny-app
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "shiny run --host 0.0.0.0 --port $PORT app:app"